### ISSUE TITLE
Bug: v4.12.0 `type perfectionist/sort-imports = unknown` type issue in Nuxt

### ISSUE THREAD

**Issue by Q16solver** [azat-io/eslint-plugin-perfectionist#520]
### Describe the bug

This is actually a bit of a weird one, so whilst doing an upgrade for the eslint plugin from v4.11.0 => v4.12.0, I noticed I was getting a type error for a nuxt artifact of eslint-typegen.d.ts type error when running nuxt typecheck through my pipelines. In v4.11.0, the eslint-typegen file doesn't seem to be generated for some reason, so this doesn't happen (or maybe it just does but it never errors so it doesn't pop up?) But it definitely seems to not like the type that the plugin is generating since it has slashes, it may be an eslint-typegen issue, but popped up when I was upgrading this eslint plugin, so I'll raise it here for now

![Image](https://github.com/user-attachments/assets/4e88d783-7494-4367-853f-9d214dce3a30)

I also get a lint type definition error when running lint which seems to be related, but eslint fallsback to unknown and continues to run

```
Failed to compile schema perfectionist/sort-imports for rule perfectionist/sort-imports. Falling back to unknown.
{
  stack: 'MissingPointerError: Missing $ref pointer "#/definitions/is-line-length". Token "definitions" does not exist.\n' +
    '    at Pointer.resolve (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\pointer.js:129:23)\n' +
    '    at $Ref.resolve (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\ref.js:111:38)\n' +   
    '    at $Refs._resolve (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\refs.js:168:21)\n' +
    '    at dereference$Ref (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\dereference.js:191:27)\n' +
    '    at crawl (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\dereference.js:105:40)\n' +  
    '    at crawl (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\dereference.js:136:44)\n' +  
    '    at crawl (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\dereference.js:136:44)\n' +  
    '    at crawl (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\dereference.js:136:44)\n' +  
    '    at crawl (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\dereference.js:136:44)\n' +  
    '    at dereference (C:\\Users\\...\\node_modules\\.pnpm\\@apidevtools+json-schema-ref-parser@11.9.3\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\dereference.js:55:26)',
  code: 'EMISSINGPOINTER',
  name: 'MissingPointerError',
  message: 'Missing $ref pointer "#/definitions/is-line-length". Token "definitions" does not exist.',
  source: 'c:/Users/.../packages/shared/',        
  path: null,
  toJSON: [Function: toJSON],
  targetToken: 'definitions',
  targetRef: '#/definitions/is-line-length',
  targetFound: '#',
  parentPath: '#/items/definitions/max-line-length-requires-line-length-type/anyOf/1',
  footprint: 'null+c:/Users/.../packages/shared/+EMISSINGPOINTER+Missing $ref pointer "#/definitions/is-line-length". Token "definitions" does not exist.',
  toString: [Function: toString]
}
```

### Code example

The eslint config I have is a little complicated, I'll link to it here https://github.com/Esposter/Esposter/blob/main/packages/configuration/eslint/nuxtPlugin.js
in case it's of any use

### ESLint version

v9.25.1

### ESLint Plugin Perfectionist version

v4.12.0

### Validations

- [x] Read the [docs](https://perfectionist.dev).
- [x] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

**Comment by hugop95** [comment]
Hi @Q16solver ,

Thank you for your issue, a fix is on the way.

Regarding the generated types themselves, an issue has been created in the `eslint-typegen` repo [here](https://github.com/antfu/eslint-typegen/issues/10).

**Comment by azat-io** [comment]
Thank you for your issue!

Fixed in b5316186106e672fb57796ac5fd221c2066af303.
Released in [4.12.1](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.12.0).

**Comment by Q16solver** [comment]
@azat-io  Thanks for the fix! I've just upgraded to it and it seems like the typechecking is now working as usual, the lint --fix is still showing a slight warning/error though, should I open a new issue for this?

![Image](https://github.com/user-attachments/assets/45fa5c04-716f-44c9-b7b8-66f97d98fa2a)

**Comment by hugop95** [comment]
https://github.com/azat-io/eslint-plugin-perfectionist/issues/525
